-- Broad canon shows seed for future question and Heads Up authoring.

insert into public.shows (show_key, display_name, alt_names)
values
  ('42nd_street', '42nd Street', '[]'::jsonb),
  ('a_chorus_line', 'A Chorus Line', '[]'::jsonb),
  ('a_little_night_music', 'A Little Night Music', '[]'::jsonb),
  ('aida', 'Aida', '["Disney''s Aida"]'::jsonb),
  ('aladdin', 'Aladdin', '[]'::jsonb),
  ('almost_famous', 'Almost Famous', '[]'::jsonb),
  ('annie', 'Annie', '[]'::jsonb),
  ('annie_get_your_gun', 'Annie Get Your Gun', '[]'::jsonb),
  ('assassins', 'Assassins', '[]'::jsonb),
  ('avenue_q', 'Avenue Q', '[]'::jsonb),
  ('back_to_the_future', 'Back to the Future', '[]'::jsonb),
  ('bandstand', 'Bandstand', '[]'::jsonb),
  ('bat_boy', 'Bat Boy', '[]'::jsonb),
  ('beauty_and_the_beast', 'Beauty and the Beast', '[]'::jsonb),
  ('be_more_chill', 'Be More Chill', '[]'::jsonb),
  ('beetlejuice', 'Beetlejuice', '[]'::jsonb),
  ('big_fish', 'Big Fish', '[]'::jsonb),
  ('billy_elliot', 'Billy Elliot', '[]'::jsonb),
  ('blood_brothers', 'Blood Brothers', '[]'::jsonb),
  ('bonnie_and_clyde', 'Bonnie & Clyde', '["Bonnie and Clyde"]'::jsonb),
  ('bring_it_on', 'Bring It On', '[]'::jsonb),
  ('cabaret', 'Cabaret', '[]'::jsonb),
  ('carrie', 'Carrie', '[]'::jsonb),
  ('carousel', 'Carousel', '[]'::jsonb),
  ('catch_me_if_you_can', 'Catch Me If You Can', '[]'::jsonb),
  ('cats', 'Cats', '[]'::jsonb),
  ('charlie_and_the_chocolate_factory', 'Charlie and the Chocolate Factory', '[]'::jsonb),
  ('chess', 'Chess', '[]'::jsonb),
  ('chicago', 'Chicago', '[]'::jsonb),
  ('come_from_away', 'Come From Away', '[]'::jsonb),
  ('company', 'Company', '[]'::jsonb),
  ('dear_evan_hansen', 'Dear Evan Hansen', '[]'::jsonb),
  ('dreamgirls', 'Dreamgirls', '[]'::jsonb),
  ('evita', 'Evita', '[]'::jsonb),
  ('falsettos', 'Falsettos', '[]'::jsonb),
  ('fiddler_on_the_roof', 'Fiddler on the Roof', '[]'::jsonb),
  ('finding_neverland', 'Finding Neverland', '[]'::jsonb),
  ('follies', 'Follies', '[]'::jsonb),
  ('frozen', 'Frozen', '[]'::jsonb),
  ('fun_home', 'Fun Home', '[]'::jsonb),
  ('funny_girl', 'Funny Girl', '[]'::jsonb),
  ('groundhog_day', 'Groundhog Day', '[]'::jsonb),
  ('guys_and_dolls', 'Guys and Dolls', '[]'::jsonb),
  ('gypsy', 'Gypsy', '[]'::jsonb),
  ('hair', 'Hair', '[]'::jsonb),
  ('hadestown', 'Hadestown', '[]'::jsonb),
  ('hamilton', 'Hamilton', '[]'::jsonb),
  ('hairspray', 'Hairspray', '[]'::jsonb),
  ('hedwig_and_the_angry_inch', 'Hedwig and the Angry Inch', '[]'::jsonb),
  ('hello_dolly', 'Hello, Dolly!', '["Hello Dolly"]'::jsonb),
  ('heathers', 'Heathers', '[]'::jsonb),
  ('hercules', 'Hercules', '[]'::jsonb),
  ('high_school_musical', 'High School Musical', '[]'::jsonb),
  ('in_the_heights', 'In the Heights', '[]'::jsonb),
  ('into_the_woods', 'Into the Woods', '[]'::jsonb),
  ('jagged_little_pill', 'Jagged Little Pill', '[]'::jsonb),
  ('jersey_boys', 'Jersey Boys', '[]'::jsonb),
  ('jesus_christ_superstar', 'Jesus Christ Superstar', '[]'::jsonb),
  ('joseph_and_the_amazing_technicolor_dreamcoat', 'Joseph and the Amazing Technicolor Dreamcoat', '["Joseph"]'::jsonb),
  ('kathy_and_stella_solve_a_murder', 'Kathy and Stella Solve a Murder!', '[]'::jsonb),
  ('kimberly_akimbo', 'Kimberly Akimbo', '[]'::jsonb),
  ('kinky_boots', 'Kinky Boots', '[]'::jsonb),
  ('legally_blonde', 'Legally Blonde', '[]'::jsonb),
  ('les_miserables', 'Les Misérables', '["Les Miserables", "Les Mis"]'::jsonb),
  ('little_shop_of_horrors', 'Little Shop of Horrors', '["Little Shop"]'::jsonb),
  ('mamma_mia', 'Mamma Mia!', '[]'::jsonb),
  ('man_of_la_mancha', 'Man of La Mancha', '[]'::jsonb),
  ('mary_poppins', 'Mary Poppins', '[]'::jsonb),
  ('matilda', 'Matilda', '["Matilda the Musical"]'::jsonb),
  ('mean_girls', 'Mean Girls', '[]'::jsonb),
  ('merrily_we_roll_along', 'Merrily We Roll Along', '[]'::jsonb),
  ('miss_saigon', 'Miss Saigon', '[]'::jsonb),
  ('monty_pythons_spamalot', 'Monty Python''s Spamalot', '["Spamalot"]'::jsonb),
  ('motown_the_musical', 'Motown the Musical', '[]'::jsonb),
  ('moulin_rouge', 'Moulin Rouge!', '["Moulin Rouge The Musical"]'::jsonb),
  ('mrs_doubtfire', 'Mrs Doubtfire', '[]'::jsonb),
  ('mj_the_musical', 'MJ the Musical', '[]'::jsonb),
  ('my_fair_lady', 'My Fair Lady', '[]'::jsonb),
  ('my_son_pinocchio', 'My Son Pinocchio', '[]'::jsonb),
  ('newsies', 'Newsies', '[]'::jsonb),
  ('next_to_normal', 'Next to Normal', '["NTN"]'::jsonb),
  ('oklahoma', 'Oklahoma!', '[]'::jsonb),
  ('oliver', 'Oliver!', '[]'::jsonb),
  ('once', 'Once', '[]'::jsonb),
  ('on_the_town', 'On the Town', '[]'::jsonb),
  ('operation_mincemeat', 'Operation Mincemeat', '["Operation Mincemeat: A New Musical", "Operation Mincemeat: The Musical"]'::jsonb),
  ('pacific_overtures', 'Pacific Overtures', '[]'::jsonb),
  ('parade', 'Parade', '[]'::jsonb),
  ('passion', 'Passion', '[]'::jsonb),
  ('pippin', 'Pippin', '[]'::jsonb),
  ('rent', 'Rent', '[]'::jsonb),
  ('rock_of_ages', 'Rock of Ages', '[]'::jsonb),
  ('school_of_rock', 'School of Rock', '[]'::jsonb),
  ('seussical', 'Seussical', '[]'::jsonb),
  ('shrek', 'Shrek', '["Shrek the Musical"]'::jsonb),
  ('sister_act', 'Sister Act', '[]'::jsonb),
  ('six', 'Six', '[]'::jsonb),
  ('something_rotten', 'Something Rotten!', '[]'::jsonb),
  ('south_pacific', 'South Pacific', '[]'::jsonb),
  ('spongebob_squarepants', 'SpongeBob SquarePants', '["SpongeBob Musical", "The SpongeBob Musical"]'::jsonb),
  ('spring_awakening', 'Spring Awakening', '[]'::jsonb),
  ('standing_at_the_skys_edge', 'Standing at the Sky''s Edge', '["Standing at the Skys Edge"]'::jsonb),
  ('starlight_express', 'Starlight Express', '[]'::jsonb),
  ('sunday_in_the_park_with_george', 'Sunday in the Park with George', '[]'::jsonb),
  ('sunset_boulevard', 'Sunset Boulevard', '[]'::jsonb),
  ('sweeney_todd', 'Sweeney Todd', '["Sweeney Todd: The Demon Barber of Fleet Street"]'::jsonb),
  ('tarzan', 'Tarzan', '[]'::jsonb),
  ('the_addams_family', 'The Addams Family', '[]'::jsonb),
  ('the_bodyguard', 'The Bodyguard', '[]'::jsonb),
  ('the_book_of_mormon', 'The Book of Mormon', '[]'::jsonb),
  ('the_color_purple', 'The Color Purple', '[]'::jsonb),
  ('the_great_gatsby', 'The Great Gatsby', '[]'::jsonb),
  ('the_hunchback_of_notre_dame', 'The Hunchback of Notre Dame', '[]'::jsonb),
  ('the_king_and_i', 'The King and I', '[]'::jsonb),
  ('the_last_five_years', 'The Last Five Years', '[]'::jsonb),
  ('the_lion_king', 'The Lion King', '[]'::jsonb),
  ('the_little_mermaid', 'The Little Mermaid', '[]'::jsonb),
  ('the_notebook', 'The Notebook', '[]'::jsonb),
  ('the_phantom_of_the_opera', 'The Phantom of the Opera', '["Phantom of the Opera", "Phantom"]'::jsonb),
  ('the_prince_of_egypt', 'The Prince of Egypt', '[]'::jsonb),
  ('the_producers', 'The Producers', '[]'::jsonb),
  ('the_rocky_horror_show', 'The Rocky Horror Show', '["Rocky Horror"]'::jsonb),
  ('the_sound_of_music', 'The Sound of Music', '[]'::jsonb),
  ('the_wiz', 'The Wiz', '[]'::jsonb),
  ('tick_tick_boom', 'Tick, Tick... Boom!', '["Tick Tick Boom"]'::jsonb),
  ('tina_the_tina_turner_musical', 'Tina: The Tina Turner Musical', '["Tina"]'::jsonb),
  ('tootsie', 'Tootsie', '[]'::jsonb),
  ('two_strangers_carry_a_cake_across_new_york', 'Two Strangers (Carry a Cake Across New York)', '["Two Strangers"]'::jsonb),
  ('urinetown', 'Urinetown', '[]'::jsonb),
  ('waitress', 'Waitress', '[]'::jsonb),
  ('we_will_rock_you', 'We Will Rock You', '[]'::jsonb),
  ('west_side_story', 'West Side Story', '[]'::jsonb),
  ('wicked', 'Wicked', '[]'::jsonb),
  ('why_am_i_so_single', 'Why Am I So Single?', '[]'::jsonb),
  ('young_frankenstein', 'Young Frankenstein', '[]'::jsonb)
on conflict (show_key)
do update set
  display_name = excluded.display_name,
  alt_names = excluded.alt_names,
  updated_at = now();
